SELECT soberano."fn_DeliveryProvider_create"('MENSAJERO_TEST_1',
											0.0,
											true,
											ARRAY['CU'],
											ARRAY['CORTA',
												'MEDIA',
												'LARGA'],
											ARRAY[100,200,300],
											'soberano.user.top');
											
SELECT * FROM soberano."fn_DeliveryProvider_modify"(1008,
											'MENSAJERO_TEST_1',
											0.0,
											true,
											ARRAY['CU','CU','CU','CU','CU','CU','CU','CU','CU','CU',
												'CU','CU','CU','CU','CU','CU','CU','CU','CU','CU',
												'CU','CU','CU','CU','CU','CU','CU','CU','CU','CU',
												'CU','CU','CU','CU','CU','CU','CU','CU','CU','CU']::character(2)[],
											ARRAY['1KM','2KM','3KM','4KM','5KM','6KM','7KM','8KM','9KM','10KM',
												'11KM','12KM','13KM','14KM','15KM','16KM','17KM','18KM','19KM','20KM',
												'21KM','22KM','23KM','24KM','25KM','26KM','27KM','28KM','29KM','30KM',
												'31KM','32KM','33KM','34KM','35KM','36KM','37KM','38KM','39KM','40KM']::character varying[],
											ARRAY[100.0,200.0,300.0,400.0,500.0,600.0,700.0,800.0,900.0,1000.0,
												1100.0,1200.0,1300.0,1400.0,1500.0,1600.0,1700.0,1800.0,1900.0,2000.0,
												2100.0,2200.0,2300.0,2400.0,2500.0,2600.0,2700.0,2800.0,2900.0,3000.0,
												3100.0,3200.0,3300.0,3400.0,3500.0,3600.0,3700.0,3800.0,3900.0,4000.0]::numeric[],
											'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A CORTA DISTANCIA',
									'_',
									'd@d.d',
									'1',
									'_',
									'CORTA',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');
									
SELECT soberano."fn_Customer_create"('CLIENTE A MEDIA DISTANCIA',
									'_',
									'd@d.d',
									'1',
									'_',
									'MEDIA',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A LARGA DISTANCIA',
									'_',
									'd@d.d',
									'1',
									'_',
									'LARGA',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 1KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'1KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 2KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'2KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 3KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'3KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 4KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'4KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 5KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'5KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 6KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'6KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 7KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'7KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 8KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'8KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 9KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'9KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 10KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'10KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 11KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'11KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 12KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'12KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 13KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'13KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 14KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'14KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 15KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'15KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 16KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'16KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 17KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'17KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 18KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'18KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 19KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'19KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 20KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'20KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 21KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'21KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 22KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'22KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 23KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'23KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 24KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'24KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 25KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'25KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 26KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'26KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 27KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'27KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 28KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'28KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 29KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'29KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 30KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'30KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 31KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'31KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 32KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'32KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 33KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'33KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 34KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'34KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 35KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'35KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 36KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'36KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 37KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'37KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 38KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'38KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 39KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'39KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');

SELECT soberano."fn_Customer_create"('CLIENTE A 40KM',
									'_',
									'd@d.d',
									'1',
									'_',
									'40KM',
									'',
									1026,
									'',
									null,
									null,
									0.0,
									'soberano.user.top');
